### ISSUE TITLE
The README makes mention of contributing to the original creator.

### ISSUE THREAD

**Issue by TopazTK** [t3dotgg/vsc-material-but-i-wont-sue-you#5]
I do not know what your stance on that would be, but I don't really know if it's the best idea to keep this in the README for a few reasons. Just wanted to grab your attention.

This can be fixed by changing the image I guess, but I do not know if this would actually conflict with Apache 2.0.

![image](https://github.com/user-attachments/assets/9b5906d5-21d2-4492-9562-4ab35ea511ef)

**Comment by Disservin** [comment]
do you have a cached version of the readme? the current one looks different with no link

**Comment by TopazTK** [comment]
It was patched out with commit c7dbdc5. Closing.
